### ISSUE TITLE
Earth issue+flickering

### ISSUE THREAD

**Issue by StarExplorerNeptune** [Its-Just-Luci/EVO#7]
![2021-03-29 (1)](https://user-images.githubusercontent.com/73246703/112916720-59d13180-90be-11eb-9b21-8158a2a2ee2b.png)
What is wrong with my earth, I have installed the latest version, and it is also flickering when I turn my camera

**Comment by Its-Just-Luci** [comment]
what are your EVE version, Scatterer version, Kopernicus version and KSP version.

also please make sure you've followed the EVO install instructions and do not have RSSVE or RVE installed

**Comment by StarExplorerNeptune** [comment]
EVE version: 1.8.0-2. Scatterer version: v0.055. Kopernicus version: 1.8.1-38. KSP version: 1.8.1.

**Comment by StarExplorerNeptune** [comment]
Another problem is that a lot of city lights are not showing up

**Comment by StarExplorerNeptune** [comment]
Do I have to have kopernicus bleeding edge instead of kopernicus planetary modifier?

**Comment by Its-Just-Luci** [comment]
> Do I have to have kopernicus bleeding edge instead of kopernicus planetary modifier?

no, you don't. Have you tried all of the troubleshooting steps on the forum page? 

"The Lights aren't showing up/ look off press alt+0, push the arrow in the EVE menu to go to textures and hit apply, go to city lights and hit apply, and if the terrain now looks off press alt+11 and map EVE clouds.

The terrain is white/invisible! 99% of the time, this is due to an improper install, read the directions. Seriously. if that doesn't work, attempt the fix above as it often fixes that issue as well"

**Comment by StarExplorerNeptune** [comment]
Oh hello Luci! I fixed this issue a while ago, but thanks for following up!
